apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: ndayizeyeadiel2/frontreactjs3
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: viteapiurl
                  key: REACT_APP_BACKEND_URL