name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Google Cloud SDK
    - name: Authenticate to Google Cloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    # 3. Configure kubectl to interact with GKE
    - name: Set up kubectl
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }}
        kubectl version --client

    # 4. Deploy Kubernetes manifests
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f .
