name: Deploy to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        install_components: 'gke-gcloud-auth-plugin'

    - name: Verify GCP credentials
      run: |
        gcloud config list project
        gcloud auth list

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
          --zone ${{ secrets.GKE_ZONE }} \
          --project ${{ secrets.GCP_PROJECT }}

    - name: Verify kubectl configuration
      run: |
        kubectl version --client
        kubectl config get-contexts
        
    - name: Deploy to Kubernetes
      run: |
        # List files in current directory
        ls -la
        # Apply all yaml files in current directory
        kubectl apply -f ./manifests
        kubectl wait --for=condition=available --timeout=300s deployment --all -n default

    - name: Verify deployment
      run: |
        kubectl get deployments -o wide
        kubectl get services -o wide
        kubectl get pods -o wide

    - name: Post-deployment cleanup
      if: always()
      run: |
        echo "Deployment process completed"
